name: simple_pdf_viewer
description: Pluging for simple pdf viewer
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin